config/routes.rb
RebelFoundation::Application.routes.draw do
  root :to => "home#index"
  resources :user
  resources :des_jobs  
  resources :dev_jobs 
  resources :designers 
  resources :developers 
    
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout   
end

app/models/des_job.rb
class DesJob
  include Mongoid::Document
  field :title, :type => String
  field :description, :type => String
  field :requirements, :type => String
  field :responsibilities, :type => String
  
  validates_presence_of :title, :description, :requirements, :responsibilities
  validates_uniqueness_of :title
end

app/models/designer.rb
class Designer
  include Mongoid::Document
  field :name, :type => String
  field :description, :type => String
  field :services, :type => String
  field :website, :type => String
  
  validates_presence_of :name, :description, :services, :website
  validates_uniqueness_of :name
end

app/models/dev_job.rb
class DevJob
  include Mongoid::Document
  field :title, :type => String
  field :description, :type => String
  field :qualifications, :type => String
  field :preferred_skills, :type => String 
  
  validates_presence_of :title, :description, :qualifications, :preferred_skills
  validates_uniqueness_of :title
end

app/models/developer.rb
class Developer
  include Mongoid::Document
  field :name, :type => String
  field :description, :type => String
  field :services, :type => String
  field :website, :type => String
  
  validates_presence_of :name, :description, :services, :website
  validates_uniqueness_of :name
end

app/models/user.rb
class User
  include Mongoid::Document
  field :provider
  field :uid
  field :name
  
  def self.create_with_omniauth(auth)  
    create! do |user|  
      user.provider = auth["provider"]  
      user.uid = auth["uid"]  
      user.name = auth["user_info"]["name"]  
    end  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base  
  protect_from_forgery  
  helper_method :current_user  
    
  private  
  def current_user  
    @current_user ||= User.find(session[:user_id]) if session[:user_id]  
  end  
end  

app/controllers/des_jobs_controller.rb
class DesJobsController < ApplicationController

  def index
    @des_jobs = DesJob.all
  end

  def show
    @des_job = DesJob.find(params[:id])
  end

  def new
    @des_job = DesJob.new
  end

  def edit
    @des_job = DesJob.find(params[:id])
  end

  def create
    @des_job = DesJob.new(params[:des_job])

    respond_to do |format|
      if @des_job.save
        format.html { redirect_to @des_job, notice: 'Des job was successfully created.' }
        format.json { render json: @des_job, status: :created, location: @des_job }
      else
        format.html { render action: "new" }
        format.json { render json: @des_job.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @des_job = DesJob.find(params[:id])

    respond_to do |format|
      if @des_job.update_attributes(params[:des_job])
        format.html { redirect_to @des_job, notice: 'Des job was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @des_job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @des_job = DesJob.find(params[:id])
    @des_job.destroy

    respond_to do |format|
      format.html { redirect_to des_jobs_url }
      format.json { head :ok }
    end
  end
end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController
  
   def index
     @designers = Designer.all
   end

   def new
     @designer = Designer.new
   end
   
   def show
     @designer = Designer.find(params[:id])
   end
   
   def create
     @designer = Designer.new(params[:designer])

      respond_to do |format|
        if @designer.save
          format.html { redirect_to @designer, notice: 'Designer Listing was successfully created.' }
          format.json { render json: @designer, status: :created, location: @designer }
        else
          format.html { render action: "new" }
          format.json { render json: @designer.errors, status: :unprocessable_entity }
        end
      end
    end
end

app/controllers/dev_jobs_controller.rb
class DevJobsController < ApplicationController

  def index
    @dev_jobs = DevJob.all
  end

  def show
    @dev_job = DevJob.find(params[:id])
  end

  def new
    @dev_job = DevJob.new
  end

  def edit
    @dev_job = DevJob.find(params[:id])
  end

  def create
    @dev_job = DevJob.new(params[:dev_job])

    respond_to do |format|
      if @dev_job.save
        format.html { redirect_to @dev_job, notice: 'Dev job was successfully created.' }
        format.json { render json: @dev_job, status: :created, location: @dev_job }
      else
        format.html { render action: "new" }
        format.json { render json: @dev_job.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @dev_job = DevJob.find(params[:id])

    respond_to do |format|
      if @dev_job.update_attributes(params[:dev_job])
        format.html { redirect_to @dev_job, notice: 'Dev job was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @dev_job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @dev_job = DevJob.find(params[:id])
    @dev_job.destroy

    respond_to do |format|
      format.html { redirect_to dev_jobs_url }
      format.json { head :ok }
    end
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController

   def index
     @developers = Developer.all
   end
   
   def new
     @developer = Developer.new
   end
   
  def show
    @developer = Developer.find(params[:id])
  end   
   
   def create
    @developer = Developer.new(params[:developer])

    respond_to do |format|
      if @developer.save
        format.html { redirect_to @developer, notice: 'Developer Listing was successfully created.' }
        format.json { render json: @developer, status: :created, location: @developer }
      else
        format.html { render action: "new" }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController  
  def create  
    auth = request.env["omniauth.auth"]  
    user = User.where(provider: auth["provider"], uid: auth["uid"])
    user = user.present? ? user.first : User.create_with_omniauth(auth) 
    session[:user_id] = user.id  
    redirect_to root_url, :notice => "Signed in!"   
  end
  
  def destroy  
  session[:user_id] = nil  
  redirect_to root_url, :notice => "Signed out!"  
end    
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/des_job_helper.rb
module DesJobHelper
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/helpers/dev_jobs_helper.rb
module DevJobsHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/des_jobs/_form.html.erb
<%= simple_form_for(@des_job) do |f| %>
    <%= f.error_notification %>
	<%= f.input :title %>
	<%= f.input :description %>
	<%= f.input :requirements %>
	<%= f.input :responsibilities %>
	<%= f.button :submit %>
<% end %>

app/views/des_jobs/edit.html.erb
<h1>Editing Designer Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @des_job %> |
<%= link_to 'Back', des_jobs_path %>

app/views/des_jobs/index.html.erb
<h1>Designer Jobs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Actions</th>
  </tr>

<% @des_jobs.each do |des_job| %>
  <tr>
  	<td><%= link_to des_job.title,  :action => 'show', :id => des_job %></td>
    <td><%= des_job.description %></td>
    <td><%= link_to 'Show', des_job %>
    <%= link_to 'Edit', edit_des_job_path(des_job) %>
    <%= link_to 'Destroy', des_job, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Des job', new_des_job_path %>

app/views/des_jobs/new.html.erb
<h1>New Designer Job</h1>

<%= render 'form' %>

<%= link_to 'Back', des_jobs_path %>

app/views/des_jobs/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Title:</b>
  <%= @des_job.title %>
</p>

<p>
  <b>Description:</b>
  <%= @des_job.description %>
</p>

<p>
  <b>Responsibilities:</b>
  <%= @des_job.responsibilities %>
</p>

<p>
  <b>Requirements:</b>
  <%= @des_job.requirements %>
</p>


<%= link_to 'Edit', edit_des_job_path(@des_job) %> |
<%= link_to 'Back', des_jobs_path %>

app/views/designers/_form.html.erb
<%= simple_form_for(@designer) do |f| %>
    <%= f.error_notification %>
	<%= f.input :name %>
	<%= f.input :description %>
	<%= f.input :services %>
	<%= f.input :website %>
	<%= f.button :submit %>
<% end %>

app/views/designers/index.html.erb
<h1>Designers Available</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Actions</th>
  </tr>

<% @designers.each do |designer| %>
  <tr>
  	<td><%= link_to designer.name,  :action => 'show', :id => designer %></td>
    <td><%= designer.description %></td>
    <td><%= link_to 'Show', designer %>
    <%= link_to 'Edit', edit_designer_path(designer) %>
    <%= link_to 'Destroy', designer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Designer', new_designer_path %>

app/views/designers/new.html.erb
<h1>New Designer Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', designers_path %>

app/views/designers/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Name:</b>
  <%= @designer.name %>
</p>

<p>
  <b>Description:</b>
  <%= @designer.description %>
</p>

<p>
  <b>Services:</b>
  <%= @designer.services %>
</p>

<p>
  <b>Website Address:</b>
  <%= @designer.website %>
</p>


<%= link_to 'Edit', edit_designer_path(@designer) %> |
<%= link_to 'Back', designers_path %>

app/views/dev_jobs/_form.html.erb
<%= simple_form_for(@dev_job) do |f| %>
    <%= f.error_notification %>
	<%= f.input :title %>
	<%= f.input :description %>
	<%= f.input :qualifications %>
	<%= f.input :preferred_skills %>
	<%= f.button :submit %>
<% end %>

app/views/dev_jobs/edit.html.erb
<h1>Editing Developer Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @dev_job %> |
<%= link_to 'Back', dev_jobs_path %>

app/views/dev_jobs/index.html.erb
<h1>Developer Jobs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Actions</th>
  </tr>

<% @dev_jobs.each do |dev_job| %>
  <tr>
    <td><%= link_to dev_job.title,  :action => 'show', :id => dev_job %></td>
    <td><%= dev_job.description %></td>
    <td><%= link_to 'Show', dev_job %>
    <%= link_to 'Edit', edit_dev_job_path(dev_job) %>
    <%= link_to 'Destroy', dev_job, confirm: 'Are you sure?', method: :delete, remote: true %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dev job', new_dev_job_path %>

app/views/dev_jobs/new.html.erb
<h1>New Developer Job</h1>

<%= render 'form' %>

<%= link_to 'Back', dev_jobs_path %>

app/views/dev_jobs/show.html.erb
<p id="notice"><%= notice %></p>

  <b>Title:</b>
  <%= @dev_job.title %>
</p>

<p>
  <b>Description:</b>
  <%= @dev_job.description %>
</p>

<p>
  <b>Qualifications:</b>
  <%= @dev_job.qualifications %>
</p>

<p>
  <b>Preferred skills:</b>
  <%= @dev_job.preferred_skills %>
</p>

<%= link_to 'Edit', edit_dev_job_path(@dev_job) %> |
<%= link_to 'Back', dev_jobs_path %>

app/views/developers/_form.html.erb
<%= simple_form_for(@developer) do |f| %>
    <%= f.error_notification %>
	<%= f.input :name %>
	<%= f.input :description %>
	<%= f.input :services %>
	<%= f.input :website %>
	<%= f.button :submit %>
<% end %>

app/views/developers/index.html.erb
<h1>Developers Available</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Actions</th>
  </tr>

<% @developers.each do |developer| %>
  <tr>
  	<td><%= link_to developer.name,  :action => 'show', :id => developer %></td>
    <td><%= developer.description %></td>
    <td><%= link_to 'Show', developer %>
    <%= link_to 'Edit', edit_developer_path(developer) %>
    <%= link_to 'Destroy', developer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Developer', new_developer_path %>

app/views/developers/new.html.erb
<h1>New Developer Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', developers_path %>

app/views/developers/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Name:</b>
  <%= @developer.name %>
</p>

<p>
  <b>Description:</b>
  <%= @developer.description %>
</p>

<p>
  <b>Services:</b>
  <%= @developer.services %>
</p>

<p>
  <b>Website Address:</b>
  <%= @developer.website %>
</p>


<%= link_to 'Edit', edit_developer_path(@developer) %> |
<%= link_to 'Back', developers_path %>

app/views/home/index.html.erb
<h1>Home</h1>
  <%= link_to 'Designer Jobs', des_jobs_path %>
  <%= link_to 'Developer Jobs', dev_jobs_path %>
  <%= link_to 'Designers Available', designers_path %>
  <%= link_to 'Developers Available', developers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Developer and Designer Matchup</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<div id="user_nav">  
  <% if current_user %>  
    Welcome, <%= current_user.name %>!  
    <%= link_to "Sign Out", signout_path %>  
  <% else %>  
    <%= link_to "Sign in with Twitter", "/auth/twitter" %> 
  <% end %> 
  <%= link_to "Home", root_path %>  
</div>  
</head>
<body>

<%= yield %>

</body>
</html>